# Generated by Django 5.0.2 on 2024-02-12 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='parked_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parked_user', models.CharField(blank=True, max_length=25)),
                ('occupied', models.BooleanField(blank=True, default=False, null=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('parked_from', models.DateTimeField()),
                ('parked_till', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='parking_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=25)),
                ('rate', models.FloatField()),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_date', models.DateTimeField()),
                ('parked_from', models.DateTimeField()),
                ('parked_till', models.DateField(blank=True, null=True)),
                ('park_fee', models.FloatField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='parking_slots',
        ),
        migrations.AddField(
            model_name='parked_slot',
            name='slot_name',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.PROTECT, to='utils.parking_slot', unique=True),
        ),
    ]
