# Generated by Django 5.0.2 on 2024-02-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_parked_slot_parking_slot_user_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parked_slot',
            name='slot_name',
            field=models.OneToOneField(max_length=25, on_delete=django.db.models.deletion.PROTECT, to='utils.parking_slot'),
        ),
    ]
