# Generated by Django 5.0.2 on 2024-02-12 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_parked_slot_slot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parked_slot',
            name='parked_from',
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 9, 57, 16, 719514, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='user_id',
            field=models.CharField(max_length=25),
        ),
    ]
