# Generated by Django 5.0.2 on 2024-02-12 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_remove_parked_slot_parked_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parked_slot',
            name='parked_from',
            field=models.DateField(default=datetime.datetime(2024, 2, 12, 10, 7, 5, 37320, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 10, 7, 5, 38609, tzinfo=datetime.timezone.utc)),
        ),
    ]
