# Generated by Django 5.0.2 on 2024-02-12 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_parked_slot_parked_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_history',
            name='park_date',
        ),
        migrations.AlterField(
            model_name='parked_slot',
            name='parked_from',
            field=models.DateField(default=datetime.datetime(2024, 2, 12, 11, 19, 54, 923541, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 11, 19, 54, 924912, tzinfo=datetime.timezone.utc)),
        ),
    ]
