# Generated by Django 5.0.2 on 2024-02-12 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_remove_user_history_park_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parked_slot',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 12, 17, 51, 631626, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='parked_slot',
            name='parked_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 12, 17, 51, 633023, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
