# Generated by Django 5.0.2 on 2024-02-12 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_rename_slot_name_parking_slot_slot_slot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking_slot',
            old_name='slot_slot',
            new_name='slot_name',
        ),
        migrations.AlterField(
            model_name='parked_slot',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 16, 31, 10, 380892, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 16, 31, 10, 382323, tzinfo=datetime.timezone.utc)),
        ),
    ]
