# Generated by Django 5.0.2 on 2024-02-12 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_rename_slot_slot_parking_slot_slot_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parked_slot',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 16, 37, 58, 202053, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='parked_slot',
            name='slot_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 16, 37, 58, 203364, tzinfo=datetime.timezone.utc)),
        ),
    ]
