# Generated by Django 5.0.2 on 2024-02-12 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_alter_parked_slot_parked_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parked_slot',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 16, 37, 59, 658762, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 16, 37, 59, 662250, tzinfo=datetime.timezone.utc)),
        ),
    ]
