# Generated by Django 5.0.2 on 2024-02-12 16:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_alter_parked_slot_parked_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parked_slot',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 16, 38, 17, 611295, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='parked_slot',
            name='slot_name',
            field=models.OneToOneField(max_length=25, on_delete=django.db.models.deletion.PROTECT, to='utils.parking_slot'),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 16, 38, 17, 612571, tzinfo=datetime.timezone.utc)),
        ),
    ]
