# Generated by Django 5.0.2 on 2024-02-13 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_alter_parked_slot_parked_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parked_slot',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 7, 1, 45, 829578, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='parked_slot',
            name='slot_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 7, 1, 45, 830921, tzinfo=datetime.timezone.utc)),
        ),
    ]
