# Generated by Django 5.0.2 on 2024-02-13 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0021_alter_parked_slot_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parked_slot',
            name='amount',
            field=models.DateTimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='parked_slot',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 8, 26, 5, 809090, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='park_fee',
            field=models.DateTimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 8, 26, 5, 810344, tzinfo=datetime.timezone.utc)),
        ),
    ]
