# Generated by Django 5.0.2 on 2024-02-13 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0026_alter_parked_slot_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parked_slot',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parked_slot',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 8, 52, 42, 558346, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='park_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 8, 52, 42, 559700, tzinfo=datetime.timezone.utc)),
        ),
    ]
