# Generated by Django 5.0.2 on 2024-02-13 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0030_remove_parked_slot_occupied_parking_slot_occupied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25)),
                ('review', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='parked_slot',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 15, 7, 24, 942262, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 15, 7, 24, 943572, tzinfo=datetime.timezone.utc)),
        ),
    ]
