# Generated by Django 5.0.2 on 2024-02-13 15:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0031_user_review_alter_parked_slot_parked_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parked_slot',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 15, 49, 35, 800185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='parked_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 15, 49, 35, 801415, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='user_id',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=25)),
                ('reply', models.CharField(max_length=255)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.user_review')),
            ],
        ),
    ]
